---

# Expose some of the Home Assistant entities to HomeKit.
- name: "hass bridge"
  port: 21063 # default port for bridge
  mode: "bridge"
  filter:
    include_domains:
      - "light"
      - "fan"
      - "script"
    include_entities:
      - "switch.wol_tim_win10"
    exclude_entities:
      - "light.tim"
      - "light.decke1"
      - "light.decke2"
  