- alias: Set default theme
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: frontend.set_theme
    metadata: {}
    data:
      mode: dark
      name: main
  mode: single
  id: 55cd2163258f48ce8de69271ec662950
- alias: Increment counter on available updates
  description: ''
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      domain: update
  condition:
    condition: template
    value_template: '"{{ trigger.event.data.entity_id.startswith(''update.'') and
      trigger.event.data.old_state.state == ''off'' and trigger.event.data.new_state.state
      == ''on'' }}"

      '
  actions:
  - action: counter.increment
    target:
      entity_id: counter.updates_available
  id: 9b0947b408e14c76b870be64e8e3b452
- alias: Decrement counter on completed updates
  description: ''
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      domain: update
  condition:
    condition: template
    value_template: '"{{ trigger.event.data.entity_id.startswith(''update.'') and
      trigger.event.data.old_state.state == ''on'' and trigger.event.data.new_state.state
      == ''off'' }}"

      '
  actions:
  - action: counter.decrement
    target:
      entity_id: counter.updates_available
  id: 5fa89a73b47849b3bd1ec9743e96ff92
- id: '1770931013807'
  alias: Schalter oben (Wendeltreppe)
  description: ''
  use_blueprint:
    path: censay/ikea-bilresa-e2489-matter-smart-button.yaml
    input:
      target_device: 59921624cc4d6e91954a2b6d5347e50c
      button1_event: event.bilresa_dual_button_taste_1
      button2_event: event.bilresa_dual_button_taste_2
      button1_single:
      - action: switch.turn_on
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
      button2_single:
      - action: switch.turn_off
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
- id: '1771002623483'
  alias: Wendeltreppe Bewegung
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggspray-e2494-matter-motion-sensor.yaml
    input:
      motion_entity: binary_sensor.myggspray_wrlss_mtn_sensor_belegung
      use_time_window: true
      active_start_time: 00:00:01
      active_end_time: 06:00:00
      motion_on_action:
      - action: switch.turn_on
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
      motion_off_action:
      - action: switch.turn_off
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
      illuminance_entity: sensor.myggspray_wrlss_mtn_sensor_beleuchtungsstarke
      motion_cutoff: 10
- id: '1771064103877'
  alias: Wendeltreppe Bewegung 1
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggspray-e2494-matter-motion-sensor.yaml
    input:
      motion_entity: binary_sensor.myggspray_wrlss_mtn_sensor_belegung
      use_time_window: true
      active_start_time: '17:30:00'
      active_end_time: '23:59:59'
      motion_on_action:
      - action: switch.turn_on
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
      motion_off_action:
      - action: switch.turn_off
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
      no_motion_wait: 900
      illuminance_entity: sensor.myggspray_wrlss_mtn_sensor_beleuchtungsstarke
      motion_cutoff: 10
- id: '1771064312499'
  alias: Wendeltreppe aus
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
  conditions:
  - condition: device
    type: is_on
    device_id: 2c48734a3acd393a8dcc7d2bed0cf68f
    entity_id: d890cdfd11a38b481b5ce6d80dcc8186
    domain: switch
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      device_id: 2c48734a3acd393a8dcc7d2bed0cf68f
    data: {}
  mode: single
- id: '1771074543969'
  alias: Schalter WoZi (Lampe, Tür)
  description: ''
  use_blueprint:
    path: censay/ikea-bilresa-e2489-matter-smart-button.yaml
    input:
      target_device: c051540fe3d25cb6486b17adf3dd65fa
      button1_event: event.bilresa_dual_button_taste_1_2
      button2_event: event.bilresa_dual_button_taste_2_2
      button1_single:
      - action: switch.turn_on
        metadata: {}
        target:
          entity_id: switch.steckdose_1
        data: {}
      button2_single:
      - action: switch.turn_off
        metadata: {}
        target:
          entity_id: switch.steckdose_1
        data: {}
      button1_double:
      - device_id: 9f377aa006f8867e298f4fa34766c8d6
        domain: lock
        entity_id: e9250ee136c3b0ce159f61d9306ba459
        type: open
      button2_double:
      - device_id: 84720fb7cce611c026538280e3f1c98d
        domain: lock
        entity_id: 1cb8b549f4b73baa86177eb2c27d079a
        type: open
- id: '1771612913799'
  alias: Wendeltreppe Bewegung 1a
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggspray-e2494-matter-motion-sensor.yaml
    input:
      motion_entity: binary_sensor.myggspray_wrlss_mtn_sensor_belegung
      use_time_window: true
      active_start_time: '17:30:00'
      active_end_time: '23:59:59'
      motion_on_action:
      - action: switch.turn_on
        metadata: {}
        target:
          entity_id: switch.steckdose_2
        data: {}
      motion_off_action: []
      no_motion_wait: 900
      illuminance_entity: sensor.myggspray_wrlss_mtn_sensor_beleuchtungsstarke
      motion_cutoff: 10
- id: '1773342058932'
  alias: Garagenlicht Bewegung 1
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggspray-e2494-matter-motion-sensor.yaml
    input:
      motion_entity: binary_sensor.myggspray_wrlss_mtn_sensor_belegung_2
      use_time_window: true
      active_start_time: '20:00:00'
      active_end_time: 06:00:00
      no_motion_wait: 300
      motion_on_action:
      - type: turn_on
        device_id: 45ece56ca9a6bbee1e0d7542b1c3ea48
        entity_id: abb2c63ab1a3987d0c200a975d07d70f
        domain: switch
      motion_off_action:
      - type: turn_on
        device_id: 45ece56ca9a6bbee1e0d7542b1c3ea48
        entity_id: abb2c63ab1a3987d0c200a975d07d70f
        domain: switch
      motion_cutoff: 2
      illuminance_entity: sensor.myggspray_wrlss_mtn_sensor_beleuchtungsstarke_2
- id: '1773344935228'
  alias: Waschmaschine fertig
  description: ''
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.shelly_waschmaschine_leistung
      starting_threshold: 20
      actions:
      - action: notify.notify
        metadata: {}
        data:
          title: Die Waschmaschine ist fertig
          message: Die Wäsche will aus dem Bällebad geholt werden
      - action: python_script.set_state
        metadata: {}
        data:
          entity_id: binary_sensor.waschmaschine
          state: 'off'
      pre_actions:
      - action: python_script.set_state
        metadata: {}
        data:
          entity_id: binary_sensor.waschmaschine
          state: 'on'
- id: '1773589912289'
  alias: Garage aus
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
  conditions:
  - type: is_illuminance
    condition: device
    device_id: e9d5a98049e39038486cb2125d9e1ecd
    entity_id: 367e9d050025bc4afaad4b5dc1e7e122
    domain: sensor
    above: 10
  actions:
  - type: turn_on
    device_id: 45ece56ca9a6bbee1e0d7542b1c3ea48
    entity_id: abb2c63ab1a3987d0c200a975d07d70f
    domain: switch
  mode: single
- id: '1773684781535'
  alias: Garagenlicht Bewegung 2
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggspray-e2494-matter-motion-sensor.yaml
    input:
      motion_entity: binary_sensor.myggspray_wrlss_mtn_sensor_belegung_3
      use_time_window: true
      active_start_time: '20:00:00'
      active_end_time: 06:00:00
      no_motion_wait: 300
      motion_on_action:
      - type: turn_on
        device_id: 45ece56ca9a6bbee1e0d7542b1c3ea48
        entity_id: abb2c63ab1a3987d0c200a975d07d70f
        domain: switch
      motion_off_action:
      - type: turn_on
        device_id: 45ece56ca9a6bbee1e0d7542b1c3ea48
        entity_id: abb2c63ab1a3987d0c200a975d07d70f
        domain: switch
      motion_cutoff: 2
      illuminance_entity: sensor.myggspray_wrlss_mtn_sensor_beleuchtungsstarke_2
- id: '1773685138681'
  alias: Eingangstür offen
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggbett-e2492-matter-door-sensor.yaml
    input:
      door_entity: binary_sensor.myggbett_door_window_sensor_tur
      wait_opened_long: 1800
      action_opened_long:
      - action: notify.notify
        metadata: {}
        data:
          message: Eingangstür ist seit 30 Minuten offen
      - action: python_script.set_state
        metadata: {}
        data:
          entity_id: binary_sensor.eingangstur
          state: 'on'
      action_closed_immediate:
      - action: automation.trigger
        data:
          skip_condition: false
        target:
          entity_id: automation.eingangstur_geschlossen
- id: '1774027214024'
  alias: Eingangstür geschlossen
  description: ''
  triggers: []
  conditions:
  - condition: state
    entity_id: binary_sensor.eingangstuer
    state:
    - 'on'
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Die Eingangstür ist wieder zu.
  - action: python_script.set_state
    metadata: {}
    data:
      entity_id: binary_sensor.eingangstur
      state: 'off'
  mode: single
- id: '1774027263684'
  alias: Eingang BAK
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggbett-e2492-matter-door-sensor.yaml
    input:
      door_entity: binary_sensor.myggbett_door_window_sensor_tur
      wait_opened_long: 1800
      action_opened_long:
      - action: notify.notify
        metadata: {}
        data:
          message: Eingangstür ist seit 30 Minuten offen
      - action: python_script.set_state
        metadata: {}
        data:
          entity_id: binary_sensor.eingangstur
          state: 'on'
      action_closed_immediate:
      - action: notify.notify
        metadata: {}
        data:
          message: Die Tür ist wieder zu.
      - action: python_script.set_state
        metadata: {}
        data:
          entity_id: binary_sensor.eingangstur
          state: 'off'
- id: '1774193621193'
  alias: Schiebetür offen
  description: ''
  use_blueprint:
    path: aledziko/ikea-myggbett-e2492-matter-door-sensor.yaml
    input:
      door_entity: binary_sensor.myggbett_door_window_sensor_tur_3
      wait_opened_long: 1800
      action_opened_long:
      - action: notify.notify
        metadata: {}
        data:
          message: Schiebetür Garage ist seit 30 Minuten offen
      - action: python_script.set_state
        metadata: {}
        data:
          entity_id: binary_sensor.schiebetuer
          state: 'on'
      action_closed_immediate:
      - action: automation.trigger
        data:
          skip_condition: false
        target:
          entity_id:
          - automation.schiebetur_geschlossen
- id: '1774193686474'
  alias: Schiebetür geschlossen
  description: ''
  triggers: []
  conditions:
  - condition: state
    entity_id: binary_sensor.schiebetuer
    state:
    - 'on'
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Die Schiebetür ist wieder zu.
  - action: python_script.set_state
    metadata: {}
    data:
      entity_id: binary_sensor.schiebetuer
      state: 'off'
  mode: single
