# Add in 'SMB Extras' under https://unraid.eghostname/Settings/SMB

# Run 'testparm' to verify the config is correct after
# you modified it.

# https://gist.github.com/fschiettecatte/02d61e3d36c5f8d36b
# https://www.samba.org/samba/docs/current/man-html/vfs_fruit.8.html
# https://wiki.samba.org/index.php/
# https://www.mankier.com/8/vfs_fruit

[global]
    # Linux supports kernel oplocks
    # Apple changed something with their SMB client in macOS 13 (Ventura) causing
    # it to place opportunitics locks on files being edited resulting in a
    # 'text file busy' error on the Linux side when attempting to execute the script.
    # Setting 'kernel oplocks = yes' works around this issue.
    # Reported to Apple as FB11738061, reported as fixed? on Oct 16, 2025
    # Present in macOS 14 (Sonoma) (Accessing Linux Samba 4.20.x)
    # Present in macOS 15 (Sequoia) (Accessing Linux Samba 4.21.x)
    # Fixed? in macOS 26.2 (Tahoe) (Accessing Linux Samba 4.22.x)
#    kernel oplocks = yes

    # Added for Mac Client support
    min protocol = SMB3
    ea support = yes
    fruit:nfs_aces = no
    fruit:model = MacSamba

[private-tfb]
    path = /mnt/user/private-tfb

    vfs objects = fruit streams_xattr
    fruit:resource = file
    fruit:metadata = stream
    fruit:encoding = native
    fruit:veto_appledouble = no
    readdir_attr:aapl_max_access = no
    readdir_attr:aapl_finder_info = no
    readdir_attr:aapl_rsize = no
    fruit:wipe_intentionally_left_blank_rfork = yes
    fruit:delete_empty_adfiles = yes
    fruit:zero_file_id = yes
    fruit:posix_rename = yes
    fruit:posix_opens = yes

    veto files = /._*/.DS_Store/
    delete veto files = yes

    spotlight = yes
    # Let mac search index the share, not server
    spotlight backend = noindex