mqtt:
  enabled: true
  host: '{FRIGATE_MQTT_HOST}'
  port: 8883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  topic_prefix: hass/frigate
  client_id: frigate
  tls_ca_certs: /config/certs/root_CA.crt
  tls_insecure: false

tls:
  enabled: false # disable tls for http, as handled by reverse proxy

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy  # record audio

detectors:
  coral:
    type: edgetpu
    device: pci
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5

record:
  enabled: true
  # When any motion is detected
  alerts:
    retain:
      days: 30
  # When a special object is detected in the set area
  detections:
    retain:
      days: 90
  continuous:
    days: 0
  motion:
    days: 7
snapshots:
  enabled: true
  retain:
    default: 365

go2rtc:
  streams:
    reolink1_record:
      - rtsp://{FRIGATE_REOLINK1_USER}:{FRIGATE_REOLINK1_PASSWORD}@{FRIGATE_REOLINK1_IP}/Preview_01_main
      - ffmpeg:reolink1_record#input=rtsp/tcp#audio=opus
    reolink1_live:
      - rtsp://{FRIGATE_REOLINK1_USER}:{FRIGATE_REOLINK1_PASSWORD}@{FRIGATE_REOLINK1_IP}/Preview_01_sub #backchannel=0
      # https://docs.frigate.video/configuration/camera_specific/#reolink-cameras
      # https://github.com/blakeblackshear/frigate/issues/9159#issuecomment-1881147182
      - ffmpeg:reolink1_live#input=rtsp/udp#audio=copy#audio=opus
    reolink1_detect:
      - ffmpeg:reolink1_live
    
    reolink2_record:
      - rtsp://{FRIGATE_REOLINK2_USER}:{FRIGATE_REOLINK2_PASSWORD}@{FRIGATE_REOLINK2_IP}/Preview_01_main
      - ffmpeg:reolink2_record#input=rtsp/tcp#audio=opus
    reolink2_live:
      - rtsp://{FRIGATE_REOLINK2_USER}:{FRIGATE_REOLINK2_PASSWORD}@{FRIGATE_REOLINK2_IP}/Preview_01_sub #backchannel=0
      # https://docs.frigate.video/configuration/camera_specific/#reolink-cameras
      # https://github.com/blakeblackshear/frigate/issues/9159#issuecomment-1881147182
      - ffmpeg:reolink2_live#input=rtsp/udp#audio=copy#audio=opus
    reolink2_detect:
      - ffmpeg:reolink2_live

cameras:
  reolink1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink1_record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink1_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      streams:
        reolink1_record: reolink1_record
    motion:
      mask: 0.384,0.015,0.6,0.015,0.601,0.071,0.386,0.068

  reolink2:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink2_record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink2_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      streams:
        reolink2_record: reolink2_record
    motion:
      mask: 0.389,0.015,0.599,0.015,0.599,0.064,0.39,0.066
version: 0.17-0
